package com.edifixio.soc.web.controllers.servlet;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import twitter4j.Twitter;
import twitter4j.TwitterException;
import twitter4j.TwitterFactory;
import twitter4j.http.RequestToken;

import com.edifixio.soc.web.servlets.BaseServletObject;


public class SigninServlet extends BaseServletObject {
    private static final long serialVersionUID = 1L;
    private static final Log log = LogFactory.getLog(SigninServlet.class);
    
    @SuppressWarnings("deprecation")
    protected void doGet(HttpServletRequest request,HttpServletResponse response) throws ServletException, IOException 
    {
        String consumerKey=request.getSession().getAttribute("consumerKey").toString(); 
        String consumerSecret = request.getSession().getAttribute("consumerKeySecrete").toString();
        
        Twitter twitter;
        request.setCharacterEncoding("UTF-8");
        RequestToken requestToken = null;
        
        TwitterFactory twitterFactory = new TwitterFactory();
        twitter = twitterFactory.getInstance();
        
        try {
            twitter.setOAuthConsumer(consumerKey, consumerSecret);
            requestToken = twitter.getOAuthRequestToken(request.getSession().getAttribute("callbackURL").toString());
            request.getSession().setAttribute("requestToken", requestToken);
            response.sendRedirect(requestToken.getAuthenticationURL() + "&force_login=true");
        } catch (TwitterException e) {
            System.out.println("Error generated by Twitter : "+e.getMessage());
            response.sendRedirect("./twt.jsp");
        }
        request.getSession().setAttribute("twitter", twitter);
    }
}
